// Code generated by MockGen. DO NOT EDIT.
// Source: accrual.go
//
// Generated by this command:
//
//	mockgen -source=accrual.go -destination=mocks/mock_accrual_client.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/KalessinD/gophermart/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockAccrualClienttInterface is a mock of AccrualClienttInterface interface.
type MockAccrualClienttInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAccrualClienttInterfaceMockRecorder
	isgomock struct{}
}

// MockAccrualClienttInterfaceMockRecorder is the mock recorder for MockAccrualClienttInterface.
type MockAccrualClienttInterfaceMockRecorder struct {
	mock *MockAccrualClienttInterface
}

// NewMockAccrualClienttInterface creates a new mock instance.
func NewMockAccrualClienttInterface(ctrl *gomock.Controller) *MockAccrualClienttInterface {
	mock := &MockAccrualClienttInterface{ctrl: ctrl}
	mock.recorder = &MockAccrualClienttInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccrualClienttInterface) EXPECT() *MockAccrualClienttInterfaceMockRecorder {
	return m.recorder
}

// GetOrderAccrual mocks base method.
func (m *MockAccrualClienttInterface) GetOrderAccrual(ctx context.Context, orderID string) (*models.AccrualResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderAccrual", ctx, orderID)
	ret0, _ := ret[0].(*models.AccrualResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderAccrual indicates an expected call of GetOrderAccrual.
func (mr *MockAccrualClienttInterfaceMockRecorder) GetOrderAccrual(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderAccrual", reflect.TypeOf((*MockAccrualClienttInterface)(nil).GetOrderAccrual), ctx, orderID)
}
