// Code generated by MockGen. DO NOT EDIT.
// Source: common.go
//
// Generated by this command:
//
//	mockgen -source=common.go -destination=mocks/mock_common_file.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/KalessinD/gophermart/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockPersistStorageInterface is a mock of PersistStorageInterface interface.
type MockPersistStorageInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPersistStorageInterfaceMockRecorder
	isgomock struct{}
}

// MockPersistStorageInterfaceMockRecorder is the mock recorder for MockPersistStorageInterface.
type MockPersistStorageInterfaceMockRecorder struct {
	mock *MockPersistStorageInterface
}

// NewMockPersistStorageInterface creates a new mock instance.
func NewMockPersistStorageInterface(ctrl *gomock.Controller) *MockPersistStorageInterface {
	mock := &MockPersistStorageInterface{ctrl: ctrl}
	mock.recorder = &MockPersistStorageInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPersistStorageInterface) EXPECT() *MockPersistStorageInterfaceMockRecorder {
	return m.recorder
}

// Erase mocks base method.
func (m *MockPersistStorageInterface) Erase() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Erase")
	ret0, _ := ret[0].(error)
	return ret0
}

// Erase indicates an expected call of Erase.
func (mr *MockPersistStorageInterfaceMockRecorder) Erase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Erase", reflect.TypeOf((*MockPersistStorageInterface)(nil).Erase))
}

// Restore mocks base method.
func (m *MockPersistStorageInterface) Restore() (models.OrdersList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Restore")
	ret0, _ := ret[0].(models.OrdersList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Restore indicates an expected call of Restore.
func (mr *MockPersistStorageInterfaceMockRecorder) Restore() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Restore", reflect.TypeOf((*MockPersistStorageInterface)(nil).Restore))
}

// Save mocks base method.
func (m *MockPersistStorageInterface) Save(orders models.OrdersList) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", orders)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockPersistStorageInterfaceMockRecorder) Save(orders any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockPersistStorageInterface)(nil).Save), orders)
}
