// Code generated by MockGen. DO NOT EDIT.
// Source: avro.go
//
// Generated by this command:
//
//	mockgen -source=avro.go -destination=mocks/mock_avro_file.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
