// Code generated by MockGen. DO NOT EDIT.
// Source: json.go
//
// Generated by this command:
//
//	mockgen -source=json.go -destination=mocks/mock_json_file.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
