// Code generated by MockGen. DO NOT EDIT.
// Source: common.go
//
// Generated by this command:
//
//	mockgen -source=common.go -destination=mocks/mock_common.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/KalessinD/gophermart/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockSQLStorageInterface is a mock of SQLStorageInterface interface.
type MockSQLStorageInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSQLStorageInterfaceMockRecorder
	isgomock struct{}
}

// MockSQLStorageInterfaceMockRecorder is the mock recorder for MockSQLStorageInterface.
type MockSQLStorageInterfaceMockRecorder struct {
	mock *MockSQLStorageInterface
}

// NewMockSQLStorageInterface creates a new mock instance.
func NewMockSQLStorageInterface(ctrl *gomock.Controller) *MockSQLStorageInterface {
	mock := &MockSQLStorageInterface{ctrl: ctrl}
	mock.recorder = &MockSQLStorageInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSQLStorageInterface) EXPECT() *MockSQLStorageInterfaceMockRecorder {
	return m.recorder
}

// AddOrder mocks base method.
func (m *MockSQLStorageInterface) AddOrder(ctx context.Context, order *models.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddOrder", ctx, order)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddOrder indicates an expected call of AddOrder.
func (mr *MockSQLStorageInterfaceMockRecorder) AddOrder(ctx, order any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddOrder", reflect.TypeOf((*MockSQLStorageInterface)(nil).AddOrder), ctx, order)
}

// AddUser mocks base method.
func (m *MockSQLStorageInterface) AddUser(ctx context.Context, user *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUser", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUser indicates an expected call of AddUser.
func (mr *MockSQLStorageInterfaceMockRecorder) AddUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUser", reflect.TypeOf((*MockSQLStorageInterface)(nil).AddUser), ctx, user)
}

// GetOrder mocks base method.
func (m *MockSQLStorageInterface) GetOrder(ctx context.Context, orderID string) (*models.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrder", ctx, orderID)
	ret0, _ := ret[0].(*models.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrder indicates an expected call of GetOrder.
func (mr *MockSQLStorageInterfaceMockRecorder) GetOrder(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrder", reflect.TypeOf((*MockSQLStorageInterface)(nil).GetOrder), ctx, orderID)
}

// GetUser mocks base method.
func (m *MockSQLStorageInterface) GetUser(ctx context.Context, login string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, login)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockSQLStorageInterfaceMockRecorder) GetUser(ctx, login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockSQLStorageInterface)(nil).GetUser), ctx, login)
}

// Ping mocks base method.
func (m *MockSQLStorageInterface) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockSQLStorageInterfaceMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockSQLStorageInterface)(nil).Ping), ctx)
}
