// Code generated by MockGen. DO NOT EDIT.
// Source: user_common_service.go
//
// Generated by this command:
//
//	mockgen -source=user_common_service.go -destination=mocks/mock_user_common_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/KalessinD/gophermart/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockCommonActionsInterface is a mock of CommonActionsInterface interface.
type MockCommonActionsInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCommonActionsInterfaceMockRecorder
	isgomock struct{}
}

// MockCommonActionsInterfaceMockRecorder is the mock recorder for MockCommonActionsInterface.
type MockCommonActionsInterfaceMockRecorder struct {
	mock *MockCommonActionsInterface
}

// NewMockCommonActionsInterface creates a new mock instance.
func NewMockCommonActionsInterface(ctrl *gomock.Controller) *MockCommonActionsInterface {
	mock := &MockCommonActionsInterface{ctrl: ctrl}
	mock.recorder = &MockCommonActionsInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommonActionsInterface) EXPECT() *MockCommonActionsInterfaceMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockCommonActionsInterface) Login(ctx context.Context, user *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Login indicates an expected call of Login.
func (mr *MockCommonActionsInterfaceMockRecorder) Login(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockCommonActionsInterface)(nil).Login), ctx, user)
}

// Register mocks base method.
func (m *MockCommonActionsInterface) Register(ctx context.Context, user *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register.
func (mr *MockCommonActionsInterfaceMockRecorder) Register(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockCommonActionsInterface)(nil).Register), ctx, user)
}
