// Code generated by MockGen. DO NOT EDIT.
// Source: user_common_service.go
//
// Generated by this command:
//
//	mockgen -source=user_common_service.go -destination=mocks/mock_user_common_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/KalessinD/gophermart/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockCommonServiceInterface is a mock of CommonServiceInterface interface.
type MockCommonServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCommonServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockCommonServiceInterfaceMockRecorder is the mock recorder for MockCommonServiceInterface.
type MockCommonServiceInterfaceMockRecorder struct {
	mock *MockCommonServiceInterface
}

// NewMockCommonServiceInterface creates a new mock instance.
func NewMockCommonServiceInterface(ctrl *gomock.Controller) *MockCommonServiceInterface {
	mock := &MockCommonServiceInterface{ctrl: ctrl}
	mock.recorder = &MockCommonServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommonServiceInterface) EXPECT() *MockCommonServiceInterfaceMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockCommonServiceInterface) Login(ctx context.Context, user *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Login indicates an expected call of Login.
func (mr *MockCommonServiceInterfaceMockRecorder) Login(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockCommonServiceInterface)(nil).Login), ctx, user)
}

// Register mocks base method.
func (m *MockCommonServiceInterface) Register(ctx context.Context, user *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register.
func (mr *MockCommonServiceInterfaceMockRecorder) Register(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockCommonServiceInterface)(nil).Register), ctx, user)
}
