// Code generated by MockGen. DO NOT EDIT.
// Source: balance_service.go
//
// Generated by this command:
//
//	mockgen -source=balance_service.go -destination=mocks/mock_balance_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBalanceActionsInterface is a mock of BalanceActionsInterface interface.
type MockBalanceActionsInterface struct {
	ctrl     *gomock.Controller
	recorder *MockBalanceActionsInterfaceMockRecorder
	isgomock struct{}
}

// MockBalanceActionsInterfaceMockRecorder is the mock recorder for MockBalanceActionsInterface.
type MockBalanceActionsInterfaceMockRecorder struct {
	mock *MockBalanceActionsInterface
}

// NewMockBalanceActionsInterface creates a new mock instance.
func NewMockBalanceActionsInterface(ctrl *gomock.Controller) *MockBalanceActionsInterface {
	mock := &MockBalanceActionsInterface{ctrl: ctrl}
	mock.recorder = &MockBalanceActionsInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBalanceActionsInterface) EXPECT() *MockBalanceActionsInterfaceMockRecorder {
	return m.recorder
}

// Store mocks base method.
func (m *MockBalanceActionsInterface) Store(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockBalanceActionsInterfaceMockRecorder) Store(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockBalanceActionsInterface)(nil).Store), ctx)
}
