// Code generated by MockGen. DO NOT EDIT.
// Source: balance_service.go
//
// Generated by this command:
//
//	mockgen -source=balance_service.go -destination=mocks/mock_balance_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/KalessinD/gophermart/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockBalanceServiceInterface is a mock of BalanceServiceInterface interface.
type MockBalanceServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockBalanceServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockBalanceServiceInterfaceMockRecorder is the mock recorder for MockBalanceServiceInterface.
type MockBalanceServiceInterfaceMockRecorder struct {
	mock *MockBalanceServiceInterface
}

// NewMockBalanceServiceInterface creates a new mock instance.
func NewMockBalanceServiceInterface(ctrl *gomock.Controller) *MockBalanceServiceInterface {
	mock := &MockBalanceServiceInterface{ctrl: ctrl}
	mock.recorder = &MockBalanceServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBalanceServiceInterface) EXPECT() *MockBalanceServiceInterfaceMockRecorder {
	return m.recorder
}

// GetBalanceInfo mocks base method.
func (m *MockBalanceServiceInterface) GetBalanceInfo(ctx context.Context) (*models.Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalanceInfo", ctx)
	ret0, _ := ret[0].(*models.Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalanceInfo indicates an expected call of GetBalanceInfo.
func (mr *MockBalanceServiceInterfaceMockRecorder) GetBalanceInfo(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalanceInfo", reflect.TypeOf((*MockBalanceServiceInterface)(nil).GetBalanceInfo), ctx)
}

// ListWithdrawals mocks base method.
func (m *MockBalanceServiceInterface) ListWithdrawals(ctx context.Context) (models.WithdrawnList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWithdrawals", ctx)
	ret0, _ := ret[0].(models.WithdrawnList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWithdrawals indicates an expected call of ListWithdrawals.
func (mr *MockBalanceServiceInterfaceMockRecorder) ListWithdrawals(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWithdrawals", reflect.TypeOf((*MockBalanceServiceInterface)(nil).ListWithdrawals), ctx)
}

// Withdraw mocks base method.
func (m *MockBalanceServiceInterface) Withdraw(ctx context.Context, withdrawn *models.Withdrawn) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Withdraw", ctx, withdrawn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Withdraw indicates an expected call of Withdraw.
func (mr *MockBalanceServiceInterfaceMockRecorder) Withdraw(ctx, withdrawn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Withdraw", reflect.TypeOf((*MockBalanceServiceInterface)(nil).Withdraw), ctx, withdrawn)
}
