// Code generated by MockGen. DO NOT EDIT.
// Source: order_service.go
//
// Generated by this command:
//
//	mockgen -source=order_service.go -destination=mocks/mock_order_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/KalessinD/gophermart/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockOrderActionsInterface is a mock of OrderActionsInterface interface.
type MockOrderActionsInterface struct {
	ctrl     *gomock.Controller
	recorder *MockOrderActionsInterfaceMockRecorder
	isgomock struct{}
}

// MockOrderActionsInterfaceMockRecorder is the mock recorder for MockOrderActionsInterface.
type MockOrderActionsInterfaceMockRecorder struct {
	mock *MockOrderActionsInterface
}

// NewMockOrderActionsInterface creates a new mock instance.
func NewMockOrderActionsInterface(ctrl *gomock.Controller) *MockOrderActionsInterface {
	mock := &MockOrderActionsInterface{ctrl: ctrl}
	mock.recorder = &MockOrderActionsInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderActionsInterface) EXPECT() *MockOrderActionsInterfaceMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockOrderActionsInterface) List(ctx context.Context) (models.OrdersList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].(models.OrdersList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockOrderActionsInterfaceMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockOrderActionsInterface)(nil).List), ctx)
}

// Store mocks base method.
func (m *MockOrderActionsInterface) Store(ctx context.Context, orderID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, orderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockOrderActionsInterfaceMockRecorder) Store(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockOrderActionsInterface)(nil).Store), ctx, orderID)
}
