// Code generated by MockGen. DO NOT EDIT.
// Source: user_common_actions.go
//
// Generated by this command:
//
//	mockgen -source=user_common_actions.go -destination=mocks/mock_user_common_actions.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	models "github.com/KalessinD/gophermart/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockUserCommonActions is a mock of UserCommonActions interface.
type MockUserCommonActions struct {
	ctrl     *gomock.Controller
	recorder *MockUserCommonActionsMockRecorder
	isgomock struct{}
}

// MockUserCommonActionsMockRecorder is the mock recorder for MockUserCommonActions.
type MockUserCommonActionsMockRecorder struct {
	mock *MockUserCommonActions
}

// NewMockUserCommonActions creates a new mock instance.
func NewMockUserCommonActions(ctrl *gomock.Controller) *MockUserCommonActions {
	mock := &MockUserCommonActions{ctrl: ctrl}
	mock.recorder = &MockUserCommonActionsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserCommonActions) EXPECT() *MockUserCommonActionsMockRecorder {
	return m.recorder
}

// GenerateToken mocks base method.
func (m *MockUserCommonActions) GenerateToken(user *models.User, key string, expireAt time.Time) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateToken", user, key, expireAt)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateToken indicates an expected call of GenerateToken.
func (mr *MockUserCommonActionsMockRecorder) GenerateToken(user, key, expireAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateToken", reflect.TypeOf((*MockUserCommonActions)(nil).GenerateToken), user, key, expireAt)
}

// Login mocks base method.
func (m *MockUserCommonActions) Login(ctx context.Context, user *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Login indicates an expected call of Login.
func (mr *MockUserCommonActionsMockRecorder) Login(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockUserCommonActions)(nil).Login), ctx, user)
}

// Register mocks base method.
func (m *MockUserCommonActions) Register(ctx context.Context, user *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register.
func (mr *MockUserCommonActionsMockRecorder) Register(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockUserCommonActions)(nil).Register), ctx, user)
}
