// Code generated by MockGen. DO NOT EDIT.
// Source: balance_service.go
//
// Generated by this command:
//
//	mockgen -source=balance_service.go -destination=mocks/mock_balance_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBalanceServiceInterface is a mock of BalanceServiceInterface interface.
type MockBalanceServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockBalanceServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockBalanceServiceInterfaceMockRecorder is the mock recorder for MockBalanceServiceInterface.
type MockBalanceServiceInterfaceMockRecorder struct {
	mock *MockBalanceServiceInterface
}

// NewMockBalanceServiceInterface creates a new mock instance.
func NewMockBalanceServiceInterface(ctrl *gomock.Controller) *MockBalanceServiceInterface {
	mock := &MockBalanceServiceInterface{ctrl: ctrl}
	mock.recorder = &MockBalanceServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBalanceServiceInterface) EXPECT() *MockBalanceServiceInterfaceMockRecorder {
	return m.recorder
}

// Store mocks base method.
func (m *MockBalanceServiceInterface) Store(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockBalanceServiceInterfaceMockRecorder) Store(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockBalanceServiceInterface)(nil).Store), ctx)
}
