// Code generated by MockGen. DO NOT EDIT.
// Source: order_service.go
//
// Generated by this command:
//
//	mockgen -source=order_service.go -destination=mocks/mock_order_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	models "github.com/KalessinD/gophermart/internal/models"
	processors "github.com/KalessinD/gophermart/internal/processors"
	gomock "go.uber.org/mock/gomock"
)

// MockOrderServiceInterface is a mock of OrderServiceInterface interface.
type MockOrderServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockOrderServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockOrderServiceInterfaceMockRecorder is the mock recorder for MockOrderServiceInterface.
type MockOrderServiceInterfaceMockRecorder struct {
	mock *MockOrderServiceInterface
}

// NewMockOrderServiceInterface creates a new mock instance.
func NewMockOrderServiceInterface(ctrl *gomock.Controller) *MockOrderServiceInterface {
	mock := &MockOrderServiceInterface{ctrl: ctrl}
	mock.recorder = &MockOrderServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderServiceInterface) EXPECT() *MockOrderServiceInterfaceMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockOrderServiceInterface) List(ctx context.Context) (models.OrdersList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].(models.OrdersList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockOrderServiceInterfaceMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockOrderServiceInterface)(nil).List), ctx)
}

// ProcessAccrualTask mocks base method.
func (m *MockOrderServiceInterface) ProcessAccrualTask(ctx context.Context, pauseCh chan time.Duration, task *processors.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessAccrualTask", ctx, pauseCh, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessAccrualTask indicates an expected call of ProcessAccrualTask.
func (mr *MockOrderServiceInterfaceMockRecorder) ProcessAccrualTask(ctx, pauseCh, task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessAccrualTask", reflect.TypeOf((*MockOrderServiceInterface)(nil).ProcessAccrualTask), ctx, pauseCh, task)
}

// Store mocks base method.
func (m *MockOrderServiceInterface) Store(ctx context.Context, orderID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, orderID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockOrderServiceInterfaceMockRecorder) Store(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockOrderServiceInterface)(nil).Store), ctx, orderID)
}
