name: gophermart

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - master
      - 'v*'

jobs:

  build:
    runs-on: ubuntu-latest
    container: golang:1.26

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: praktikum
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download autotests binaries
        uses: robinraju/release-downloader@v1.8
        with:
          repository: Yandex-Practicum/go-autotests
          latest: true
          fileName: "*"
          out-file-path: .tools
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git safe directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26'
          cache: true
          cache-dependency-path: |
            go.sum
            Makefile

      - name: Installing Golang tools
        run: |
          apt-get update && \
          DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends --no-install-suggests ca-certificates curl gcc g++ make
          curl -sSfL https://golangci-lint.run/install.sh | sh -s v2.11.4
          mkdir -p $(go env GOPATH)/bin
          mv bin/* $(go env GOPATH)/bin

      - name: Setup autotest binary
        run: |
          chmod -R +x $GITHUB_WORKSPACE/.tools
          mv $GITHUB_WORKSPACE/.tools/gophermarttest /usr/local/bin/gophermarttest
          mv $GITHUB_WORKSPACE/.tools/random /usr/local/bin/random

      - name: Run Lint
        run: |
          make lint

      - name: Prepare binaries
        run: |
          (cd cmd/gophermart && go build -buildvcs=false -o gophermart)
          (cd cmd/accrual && chmod +x accrual_linux_amd64)

      - name: Build Gophermart binary
        run: |
          make build-gophermart

      - name: Project Tests
        run: |
          make test-go

      - name: E2E Tests
        run: |
          make test-e2e

      - name: Practicum Tests
        run: |
          gophermarttest \
            -test.v -test.run=^TestGophermart$ \
            -gophermart-binary-path=cmd/gophermart/gophermart \
            -gophermart-host=localhost \
            -gophermart-port=8080 \
            -gophermart-database-uri="postgresql://postgres:postgres@postgres/praktikum?sslmode=disable" \
            -accrual-binary-path=cmd/accrual/accrual_linux_amd64 \
            -accrual-host=localhost \
            -accrual-port=$(random unused-port) \
            -accrual-database-uri="postgresql://postgres:postgres@postgres/praktikum?sslmode=disable"

      - name: Generate Coverage Report for GitHub
        if: always()
        run: |
          echo "## 📊 Test Coverage" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          make coverage >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: /tmp/practicum-gophermart-coverage.out
          fail_ci_if_error: false
          flags: unittests
          verbose: true
          # report_type: test_results # to upload junit.xml
        continue-on-error: true